### ISSUE TITLE
body_type = HTML in v0.1.27

### ISSUE THREAD

**Issue by Earthling1980** [WinRb/Viewpoint#162]
Hey, I am using v.0.1.27 and I don't seem to be able to set the body_type to HTML. Is this supported in this version and how would I add that to my code below ?

    require 'viewpoint'
    
    include Viewpoint::EWS
    
    def email(em_to, em_cc, em_subject, em_body)
    
      # get credentials and log in
      creds=File.read('/home/earthling1980/.mailcredentials').split("\n")
      Viewpoint::EWS::EWS.endpoint='https://mail.example.com/ews/exchange.asmx'
      Viewpoint::EWS::EWS.set_auth creds[0], creds[1]
    
        Viewpoint::EWS::Message.send(   \
          em_subject,                   \
          em_body,                      \
          em_to,                          \
          em_cc
        )
    
    end
    

Thanks,
    --Nick

**Comment by jwg2s** [comment]
@zenchild also struggling with this (last thing holding us back from our upgrade).  How can you force an HTML email?

**Comment by zenchild** [comment]
@Earthling1980 If you're still on version 0.1.x look at `Viewpoint::EWS::Message.send`. You can't use that but you can see how the item is built and write your own method using a similar tactic and setting the body to HTLM.

@jwg2s Are you really still using 0.1.x?

**Comment by zenchild** [comment]
In 1.x you can do something like this:

```ruby
client.send_message(subject: "Testing", to_recipients: %w{test@example.local}) do |m|
  m.body_type = "HTML"
  m.body <<-EOF
    <b>This is a test</b>
    <a href="https://github.com/WinRb/Viewpoint/issues/162">Viewpoint Issue #162</a>
  EOF
end
```

**Comment by jwg2s** [comment]
@zenchild yeah my mistake, we're on 1.x, but I commented on this issue by mistake.  Thanks for the heads up about body_type.
