### ISSUE TITLE
Kerberos auth

### ISSUE THREAD

**Issue by prsimoes** [WinRb/Viewpoint#174]
Hello,

I'm running a Ruby on Rails website with Kerberos auth. I need to implement a module that reads email from an exchange server but I wanted to use the current kerberos authenticated user in the website to access the mailbox.

Is it possible? The Viewpoint::EWSClient.new initializer always ask for the user and pass.

**Comment by prsimoes** [comment]
I wrote a simple script with HTTPClient and GSSAPI and it worked. I'm making a simple HTTP get with the Authorize header with the token generated by the GSSAPI lib and I can authenticate against my corporate pages and the EWS endpoint. I'm just doing a simple GET and not any EWS methods though.

So, as this seems to work with the underlying HTTPClient, my doubt is how to change the Viewpoint lib to reflect this.

Let me better explain my scenario:

I want to pull emails from a shared Exchange mailbox into a kerberized web application in Rails/Apache/Passenger. When I go to this webapp, I'm automatically authenticated through the kerberos REMOTE_USER. Then, I want to fetch the emails from the Exchange mailbox and present them in the webapp. I don't want to prompt the users to enter their passwords to pull the emails, so I thought using the current Authorize header and pass it to the Viewpoint lib. Could it work like this?

Another problem is, when I don't specify a username and password on the ews_client initializer, I get an error on the .dup. The code has a comment saying:

@param [String] user The user to authenticate as. If you are using
  #   NTLM or Negotiate authentication you do not need to pass this parameter.
@param [String] pass The user password. If you are using NTLM or
  #   Negotiate authentication you do not need to pass this parameter.

so, I'm a little bit confused if these parameters are really optional or not.

**Comment by prsimoes** [comment]
I've been looking into Microsoft's EWS Managed API and they have the UseDefaultCredentials attribute that if it's set to true, it will use the domain credentials of the logged in user.

My web application will be used by users in the corporate network so they will be authenticated in the domain. Is this something that Viewpoint can do and avoid the Kerberos authentication?

**Comment by zenchild** [comment]
What you're looking to do is not possible with Viewpoint as-is and you will never be able to use the Authorized header because that is generated from a shared secret if it is NTLM or Kerberos based. In other words it is only valid for communications between the web client and the remote server.

I would bet UseDefaultCredentials is still using Kerberos under-the-covers and you could probably get that sort of thing working for your users but most of it is beyond the scope of Viewpoint.
