### ISSUE TITLE
Can't figure out how to send calendar meeting invite

### ISSUE THREAD

**Issue by erik-t** [WinRb/Viewpoint#175]
I have the following and can't figure out how to send the invitation to the required attendees. I am able to create the appointment but need it to send the request after its created.

I was hoping the following would work but no go. Please help if you can. Great work by the way.

I've tried the send_meeting_invitations and meeting flag, probably in wrong place.

``` ruby
opts = {
        :send_meeting_invitations => 'SendToAllAndSaveCopy',
        :subject => 'testing',
        :body => 'hello world',
        :start => Time.now + (60*60*2),
        :end => Time.now + (60*60*3),
        :location => 'disney',
        :required_attendees => [
            {:attendee => {:mailbox => {:email_address => 'user@email.com'}}}
        ],
        :meeting => 'true',
        :options => {
            :send_meeting_invitations => 'SendToAllAndSaveCopy'
        }
    }

    folder = cli.get_folder(:calendar)
    appointment = folder.create_item(opts)
```

I've also tried 

``` ruby
    opts = {
        send_meeting_invitations: 'SendToAllAndSaveCopy',
        items: [ {calendar_item: {} } ]
    }
```

**Comment by divyaiyer** [comment]
Hi, need a help. I trying the same opt hash mentioned above. I don't see any error, calendar entry getting created on the account which is calling API with mentioned attendee. But it is not sending email to the person who are invited. Though in the option Hash it is mentioned 

:send_meeting_invitations => 'SendToAllAndSaveCopy',

But I see while running the script, SOAP request is always taking 'SendToNone' irrespective of the value I give. Can you please advice here what would be wrong, pasting code below,

  require 'rubygems'
  require 'viewpoint' # Library for MS Outlook
   require 'viewpoint/logging/config' # For Debugging
  include Viewpoint::EWS

  endpoint = 'https://outlook.office365.com/EWS/Exchange.asmx' 
  user = 'xyz@onmicrosoft.com'
  pass = 'XXXXXXX'
  
 cli = Viewpoint::EWSClient.new endpoint, user, pass
  opts = {
          :send_meeting_invitations => 'SendToAllAndSaveCopy',
          :subject => 'My testing',
          :body => 'hello world',
          :start => Time.now + (60*60*2),
          :end => Time.now + (60*60*3),
          :location => 'disney',
         :required_attendees => [{:attendee => {:mailbox => {:email_address => 'test@microsoft.com'}}} ],
         :meeting => 'true',
         :optionns => {:send_meeting_invitations => 'SendToAllAndSaveCopy'}
 }
    folder = cli.get_folder(:calendar)
    appointment = folder.create_item(opts)


console output 

DEBUG  Viewpoint::EWS::SOAP::ExchangeWebService : Sending SOAP Request:
----------------
<?xml version="1.0"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages">
  <soap:Header>
    <t:RequestServerVersion Version="Exchange2010"/>
  </soap:Header>
  <soap:Body>
    <CreateItem xmlns="http://schemas.microsoft.com/exchange/services/2006/messages" MessageDisposition="SendAndSaveCopy" **SendMeetingInvitations="SendToNone"**>
      <SavedItemFolderId>
<t:FolderId Id="AQMkAGE4YzExAGZlOS0yNWU4LTRlYzMtYjg2MS0xNzU3NDI2Yjg0N2MALgAAAxEBO6hCwTxHn4zfntfBMXABAH+jZks5wIFLpgPmRaO9VXEAAAIBDQAAAA==" ChangeKey="AgAAABYAAAB/o2ZLOcCBS6YD5kWjvVVxAAAAAAjW"/>
      </SavedItemFolderId>
      <Items>
<t:CalendarItem>
  <t:Subject>My testing</t:Subject>
  <t:Body BodyType="Text">hello world</t:Body>
  <t:Start>2017-07-31T19:59:08+05:30</t:Start>
  <t:End>2017-07-31T20:59:08+05:30</t:End>
  <t:Location>disney</t:Location>
  <t:RequiredAttendees>
    <t:Attendee>
      <t:Mailbox>
        <t:EmailAddress>test@microsoft.com</t:EmailAddress>
      </t:Mailbox>
    </t:Attendee>
  </t:RequiredAttendees>
</t:CalendarItem>
      </Items>
    </CreateItem>
  </soap:Body>
</soap:Envelope>
