### ISSUE TITLE
Get all the Recurrences of a Recurring Meeting

### ISSUE THREAD

**Issue by cdram** [WinRb/Viewpoint#187]
Trying to fetch all the Calendar Items for a particular recurring meeting. Not sure whether am doing something wrong in the search criteria. Any help would be greatly useful!

tried the following fetch, but its throwing an error...
https://gist.github.com/shriram-r-r/2e286a56940612cf18c5

**Comment by zeeshangulzar** [comment]
@cdram Any success on it?

**Comment by cdram** [comment]
@zeeshangulzar try and use nylas!
