### ISSUE TITLE
Deleting Calendar Items (Example)

### ISSUE THREAD

**Issue by bcameron** [WinRb/Viewpoint#193]
Hi folks,
Thanks so much for all the hard work in creating the Viewpoint gem. It's extremely useful.
I've been using it to create/update appointments in the calendar however I cannot see what the correct approach is to delete a calendar item. Calling the delete! method on the calendar item does nothing. I was then hoping to find a 'delete_item' method on the containing folder however it does not seem to be available on the folder object. (I can see that there is indeed a delete_item method in the code but as I don't understand the architecture of the gem at this point it's difficult to see how it all fits together.)

It would be great to have a little example in the readme for this as it would complete the basic lifecycle of the calendar items (well, ok that's just me specific use case!).

So any tips on deleting a calendar item? Could this be a bug with the delete! operation?

Thanks a mill,
Brian.

**Comment by mrk3767** [comment]
I am having the same exact issue... If I figure it out, I will let you know!

**Comment by zenchild** [comment]
Sorry I haven't responded... I've been pretty terrible about keeping up with Viewpoint lately and there is a lot of work that needs to happen in this realm. In any case, for Calendar Items you have to send a cancellation parameter. This should let you delete items like you want:

```ruby
cal_item.delete!(:recycle, send_meeting_cancellations: "SendOnlyToAll")
```

For more information on the other available options see:
https://msdn.microsoft.com/en-us/library/office/aa562961(v=exchg.150).aspx

**Comment by mrk3767** [comment]
I actually realized this last night about 30 minutes after posting. Thank you very much for responding! I'm thinking of making a short tutorial to make this easier. I'm beginning to understand how the whole thing fits together!

**Comment by bcameron** [comment]
@zenchild: Thank you very much for your response, it slipped through the cracks due to personal email chaos and I forgot to get back to you to thank you, my apologies... Thank you for sharing your hard work and creating this gem!

**Comment by divyaiyer** [comment]
i am trying the same thing, but give an error saying 

    "error": "Could not delete Viewpoint::EWS::Types::CalendarItem. ErrorCannotDeleteObject: Object cannot be deleted."

I am trying to delete my own calendar item. Code used
@cli = Viewpoint::EWSClient.new endpoint, user, pass
 begin
         id = {"id": "AAMkADlkNDQxMjhiLTg5NTEtNGNiZS1hY2FjLWMwYmMzNTdmOWI5YwBGAAAAAAC2to7MWHE9S5kyrLJLd6jaBwBtvMpN5cq6Soa1BDYGZ/GLAAAAAAENAABtvMpN5cq6Soa1BDYGZ/GLAAAYAuG8AAA=","change_key": "DwAAABYAAABtvMpN5cq6Soa1BDYGZ/GLAAAYBHii"}
         folder = @cli.get_item(id)
         puts folder
         delete_it = folder.delete!(:recycle,send_meeting_cancellations: "SendOnlyToAll")#:recycle, send_meeting_cancellations: "SendOnlyToAll")
 rescue => e
         puts e.backtrace
     end

Can you help me with this please? @bcameron  @zenchild @mrk3767
