### ISSUE TITLE
How to create unread draft?

### ISSUE THREAD

**Issue by michalfita** [WinRb/Viewpoint#195]
Examples are rather stingy, so while it's extremely useful, not well documented.

I would like to ask for an example of preparing a draft when message in the Draft folder is left **unread** (marked bold, and indicated by a number next to folder name). I managed to prepare a draft nicely formatted in HTML, but it's left in read state - not what I want.

Thank you in advance.

**Comment by zenchild** [comment]
You used to have to mark the item unread after creation but I added some extra code to the master branch that will let you set it on creation:

```ruby
draft = cli.draft_message do |m|
  m.subject = "Test Message"
  m.body = "This is a test."
  m.to_recipients = %w{user@example.local}
  m.is_read = false
end
```

**Comment by michalfita** [comment]
Thank you very much for that!

However, it will take ages to get it as updated gem, so could you be so kind and tell me how to mark draft as unread after creation?

Thanks.

**Comment by zenchild** [comment]
A few options:

1. Put it in your Gemfile
```
gem "viewpoint", github: "WinRb/Viewpoint", ref: "96ae526"
```

2. Pull it down and build your own gem
```
git clone https://github.com/WinRb/Viewpoint.git
cd Viewpoint
rake gem
gem install viewpoint-*.gem
```
3. Run this rather archaic method
`item.send(:update_is_read_status, false)`
