### ISSUE TITLE
Automatically Retry on Incorrect Server Version

### ISSUE THREAD

**Issue by jwg2s** [WinRb/Viewpoint#202]
We have to connect to multiple versions of Exchange, so we'd like there to be some type of automatic retry when there's an incorrect server version error.

For example:

```ruby
require 'viewpoint'
include Viewpoint::EWS

endpoint = 'URL'
user = 'USERNAME'
pass = 'PASSWORD'

versions = %w(Exchange2007 Exchange2007_SP1 Exchange2010 Exchange2010_SP1 Exchange2010_SP2 Exchange2013 Exchange2013_SP1)
versions.each do |version|
  cli = Viewpoint::EWSClient.new endpoint, user, pass, :server_version => version
  break if cli.folders rescue next
end
```

Obviously this is hacky code, how would you suggest we implement this?  Can open a pull request with whatever solution

**Comment by zenchild** [comment]
This is really a job for the Autodiscover service. I've been meaning to build something to do this for awhile so I hacked together some code tonight that will determine the version for you:

https://github.com/WinRb/autodiscover_plus

You could also set Viewpoint to use the lowest version and parse the ServerVersionInfo element similar to the ServerVersionParser found in the autodiscover_plus gem.

**Comment by jwg2s** [comment]
@zenchild, what about a situation where the exchange server endpoint is different than the domain of the email?  Maybe we add a way to specify/override a domain?

**Comment by zenchild** [comment]
Then I would fall back to the method I mentioned last. Instantiate a Viewpoint::EWSClient with the lowest version and then parse out the ServerVersionInfo. I can post an example if needed.

**Comment by jwg2s** [comment]
https://github.com/WinRb/autodiscover_plus/pull/1
