### ISSUE TITLE
Office365 Redirects

### ISSUE THREAD

**Issue by jwg2s** [WinRb/Viewpoint#203]
Some of our users are experiencing 301 errors with Office365.  The endpoint we're trying to connect to is https://outlook.office365.com/EWS/Exchange.asmx, but it appears as though you are redirected to a different URL.

```
Viewpoint::EWS::Errors::ResponseError: HTTP Error Code: 301, Msg:
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/Viewpoint-a743e2ef965f/lib/ews/connection.rb:116:in `check_response'
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/Viewpoint-a743e2ef965f/lib/ews/connection.rb:93:in `post'
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/Viewpoint-a743e2ef965f/lib/ews/connection.rb:71:in `dispatch'
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/Viewpoint-a743e2ef965f/lib/ews/soap/exchange_web_service.rb:212:in `do_soap_request'
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/Viewpoint-a743e2ef965f/lib/ews/soap/exchange_data_services.rb:503:in `find_folder'
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/Viewpoint-a743e2ef965f/lib/ews/folder_accessors.rb:45:in `folders'
```

@zenchild any ideas what might be going on here?

**Comment by zenchild** [comment]
I don't know off hand. Have you checked the Autodiscover output to see what it returns as the EWS URL? This is the first I've heard of a 301 for outlook.office365.com. Let me know if  you figure it out.

**Comment by zenchild** [comment]
Did you ever figure anything out on this @jwg2s?

**Comment by jwg2s** [comment]
I believe it was caused by incorrect protocols, e.g. http instead of https input by the user.  We added some code to try different permutations of the user inputs to try to connect to what we assume they intended to enter.
