### ISSUE TITLE
NoMethodError: undefined method event_name

### ISSUE THREAD

**Issue by mr-deamon** [WinRb/Viewpoint#204]
I've been using the Viewpoint-Gem a while now. Since an update of gems, i do receive
```
NoMethodError: undefined method `event_name' for #<Viewpoint::EWSClient:0x00000002336b50>
```
Events are received correctly though, my failing command is
```
cli.event_name(events.first)
````
Searching for the function or the error does not return any usable solutions. What was changed? Was i using a deprecated feature, or where did it go?
Sorry, i'm a bit lost on that one :)

Chris

**Comment by mr-deamon** [comment]
Oups, now i know. This function was made by myself, shame on me. There's actually a pull-request for this:
https://github.com/mr-deamon/Viewpoint/commit/6f50dc16a53a84e579d3bafe3cb3c17aa6b15c0b

**Comment by zenchild** [comment]
The `event_name` method was never in the main repo. Looks like you added it yourself here => https://github.com/mr-deamon/Viewpoint/commit/6f50dc16a53a84e579d3bafe3cb3c17aa6b15c0b

**Comment by zenchild** [comment]
I'll try and have a look at the pull request. I've been pre-occupied with a lot of other projects lately and need to find some time to give to Viewpoint.

**Comment by mr-deamon** [comment]
No worries, that's okay. Im glad i found the error and sorry to occupy you by selfmade-problems :)
