### ISSUE TITLE
Bulk updating

### ISSUE THREAD

**Issue by errinlarsen** [WinRb/Viewpoint#205]
My application has its own concept of calendars and appointments. I would like to allow a user to enter their Exchange information so as to opt-in for 2-way syncing. I'm worried about throttling, however, and the initial sync might be hundred, if not thousands, of individual updates to the user's Exchange Calendar.

What's a good procedure for sending a large amount of updates to Exchange for a single user?

I see that `Viewpoint::EWS::SOAP::ExchangeDataServices#update_folder` is a thing, but it appears to be incomplete/unfinished. Any hope that will get filled in? If not, any hints on how I could implement this for the project?

**Comment by zenchild** [comment]
`#update_folder` is mainly just used for updating folder properties so I don't think that's what you want. The bulk synchronization in Exchange has mainly been one-way until Exchange 2010 where they introduced UploadItems/ExportItems. I have not played with or implemented those methods but if you'd like to have a go at it the reference docs for EWS are here for your reading pleasure: https://msdn.microsoft.com/en-us/library/bb409286(v=exchg.150).aspx
