### ISSUE TITLE
EWS throttling in Exchange & Office 365

### ISSUE THREAD

**Issue by torstenb** [WinRb/Viewpoint#212]
I just started to use the `Viewpoint` gem and as part of my initial testing I noticed that there seems to be a limit of 1,000 items being returned. E.g., following is the script I'm using:

```
#!/usr/local/bin/ruby
require 'rubygems'
require 'highline/import'
require 'viewpoint'

include Viewpoint::EWS

endpoint = 'https://outlook.office365.com/EWS/Exchange.asmx'
user = ask("Enter your username:  ") { |q| q.echo = true }
pass = ask("Enter your password:  ") { |q| q.echo = "*" }

cli = Viewpoint::EWSClient.new endpoint, user, pass

inbox = cli.get_folder(:inbox)

puts "Number of items in your inbox: ", inbox.items.count
```

The inbox I'm testing with has more than 1,000 items in it, but the count comes always back as 1,000. 
I found this article on MSDN, which may be the explanation: [EWS throttling in Exchange](https://msdn.microsoft.com/en-us/library/office/jj945066(v=exchg.150).aspx)

Is this an issue with the `Viewpoint` gem or do I need to do what I'm trying to do in a different way?

**Comment by zenchild** [comment]
It does seem to be a throttling issue in Exchange. I have not run up against this myself but here is a stackoverflow article that shows a similar scenario as you. It also references the same throttle documentation that you've posted.

http://stackoverflow.com/questions/12200109/microsoft-exchange-folders-finditems-results-limited-to-a-1000
