### ISSUE TITLE
Handsoap::Fault

### ISSUE THREAD

**Issue by antonsokolskyy** [WinRb/Viewpoint#220]
I try to make sync to EWS but got error  

`  Handsoap::Fault { :code => 'a:ErrorSchemaValidation', :reason => 'The request failed schema validation: The element 'Contact' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types' has invalid child element 'ContactsCategories' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'. List of possible elements expected: 'MimeContent, ItemId, ParentFolderId, ItemClass, Subject, Sensitivity, Body, Attachments, DateTimeReceived, Size, Categories, Importance, InReplyTo, IsSubmitted, IsDraft, IsFromMe, IsResend, IsUnmodified, InternetMessageHeaders, DateTimeSent, DateTimeCreated, ResponseObjects, ReminderDueBy, ReminderIsSet, ReminderMinutesBeforeStart, DisplayCc, DisplayTo, HasAttachments, ExtendedProperty, Culture, EffectiveRights, LastModifiedName, LastModifiedTime, FileAs, FileAsMapping, DisplayName, GivenName, Initials, MiddleName, Nickname, CompleteName, CompanyName, EmailAddresses, PhysicalAddresses, PhoneNumbers, AssistantName, Birthday, BusinessHomePage, Children, Companies, ContactSource, Department, Generation, ImAddresses, JobTitle, Manager, Mileage, OfficeLocation, PostalAddressIndex, Profession, SpouseName, Surname, WeddingAnniversary' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'.' }`

my method with hash of data

`  def contact_to_ews
    attrs = {
      :file_as => {:text => self.name},
      :given_name => {:text => self.first_name},
      :surname => {:text => self.last_name},
      :company_name => {:text => self.company},
      :job_title => {:text => self.job_title}
    }
....#more attrs here
      attrs[:contacts_categories] = {:string => groups_array}
    end `

**Comment by zenchild** [comment]
The current version of the gem has not used Handsoap for some time. You should upgrade to a more recent version (at least 1.0.0).
