### ISSUE TITLE
IsResponseRequested for Calendar Item?

### ISSUE THREAD

**Issue by benbristow** [WinRb/Viewpoint#243]
Hey,

I'm currently tying to use this Gem for creating bookings for rooms within the company I work for.

I've managed to get to the point where I'm creating bookings but I can't seem to get Exchange to send invitation requests to attendees. I've monitored webmail's request when creating an event and it seems to send '[IsResponseRequested](https://msdn.microsoft.com/en-us/library/microsoft.exchange.webservices.data.appointment.isresponserequested(v=exchg.80).aspx)' as part of the parameters.

I've tried modifying the code of Viewpoint myself to support this parameter but with no luck.

Here is my Ruby code currently:

```
  def make_booking room:, subject:, start_time:, end_time:, participants:
    participants << room.email
    calendar_folder = @client.get_folder(:calendar)
    calendar_folder.create_item(
      subject: subject,
      body: 'This booking was booked automatically through Room Bookings',
      location: room.name,
      start: start_time,
      end: end_time,
      message_disposition: 'SendAndSaveCopy',
      send_meeting_invitations: 'SendToAllAndSaveCopy',
      free_type_busy: "Busy",
      required_attendees: participants_to_attendees(participants),
      reminder_is_set: 'true',
      reminder_minutes_before_start: 10
    )
  end
```

Adding is_response_requested doesn't work and just errors.

Any ideas?

**Comment by gshutler** [comment]
Can you share the error you get when providing `is_response_requested: true`?

**Comment by benbristow** [comment]
`undefined method `is_response_requested!' for #<Viewpoint::EWS::SOAP::EwsBuilder:0x007fe6ff8875f0>`

**Comment by gshutler** [comment]
Can you try references `master` and try again, I believe bcda30ab will resolve that error.

**Comment by benbristow** [comment]
Thanks for the help. I actually wrote the exact same code myself in a fork I made to try and do it myself with no success.

There's no error now but response requests still aren't being sent. Maybe it's something else?

**Comment by gshutler** [comment]
Reviewing the code, it looks like you need to do this:


```ruby
 def make_booking room:, subject:, start_time:, end_time:, participants:
    participants << room.email
    calendar_folder = @client.get_folder(:calendar)
    item_details = {
      subject: subject,
      body: 'This booking was booked automatically through Room Bookings',
      location: room.name,
      start: start_time,
      end: end_time,
      message_disposition: 'SendAndSaveCopy',
      free_type_busy: "Busy",
      required_attendees: participants_to_attendees(participants),
      reminder_is_set: 'true',
      reminder_minutes_before_start: 10
    }
    create_opts = {
      send_meeting_invitations: 'SendToAllAndSaveCopy',
    }
    calendar_folder.create_item(item_details, create_opts)
  end
```

I think `send_meeting_invitations` needs to be an option of the creation rather than an attribute of the item.

**Comment by benbristow** [comment]
@gshutler you're a saviour. Thanks for the help!

**Comment by gshutler** [comment]
No problem, thanks for your patience. 👍
