### ISSUE TITLE
item_field_uri_map.rb: warning: key :categories is duplicated and overwritten

### ISSUE THREAD

**Issue by retorquere** [WinRb/Viewpoint#254]
The hash defined in item_field_uri_map.rb has a number of duplicate keys (such as `:categories`)

**Comment by gshutler** [comment]
Hopefully [v1.1.0](https://github.com/WinRb/Viewpoint/releases/tag/v1.1.0) resolves this.

**Comment by retorquere** [comment]
It does, thank you!
